# Generated by Django 2.0 on 2018-01-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organ.OrgUnit', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organ.Position', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organ.OrgUnit', verbose_name='org unit'),
        ),
    ]
