# Generated by Django 2.0 on 2018-01-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.BankAccount', verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='material',
            field=models.ForeignKey(limit_choices_to={'is_virtual': '0'}, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='woitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='selfhelp.WOItem', verbose_name='wo item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'partner_type': 'S'}, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
