# Generated by Django 2.0.1 on 2018-01-31 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20180108_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_sale': '1', 'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='offersheet',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='offersheet',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'partner_type': 'C'}, on_delete=django.db.models.deletion.CASCADE, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='offersheet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='offer man'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.BankAccount', verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleOrder', verbose_name='sale order'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_sale': '1', 'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'partner_type': 'C'}, on_delete=django.db.models.deletion.CASCADE, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sales man'),
        ),
    ]
