# Generated by Django 2.0.1 on 2018-01-31 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0002_auto_20180108_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfhelp.Activity', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, limit_choices_to={'tp': 20}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfhelp.Loan', verbose_name='loan record'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organ.OrgUnit', verbose_name='cost center'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfhelp.WorkOrder', verbose_name='work order'),
        ),
        migrations.AlterField(
            model_name='reimbursementitem',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.ExpenseAccount', verbose_name='expenses account'),
        ),
        migrations.AlterField(
            model_name='reimbursementitem',
            name='reimbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfhelp.Reimbursement', verbose_name='reimbursement'),
        ),
        migrations.AlterField(
            model_name='woextravalue',
            name='param_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.ExtraParam', verbose_name='extra param'),
        ),
        migrations.AlterField(
            model_name='woitem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='woitem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selfhelp.WorkOrder', verbose_name='refer wo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
